Table Category {
  id uuid [pk]
  name varchar [not null]
  createdAt timestamp
  updatedAt timestamp
}

Table User {
  id uuid [pk]
  email varchar [not null]
  password varchar [not null]
  createdAt timestamp
  updatedAt timestamp
}

Enum roleName {
  staff
  admin
}

Table Profile  {
  id uuid [pk]
  username varchar [null]
  imageUrl varchar [null]
  fullname varchar [null]
  dateOfBirth date [null]
  UserId uuid [ref: - User.id] // 1:1 Relationship
  role roleName [default: 'staff']
  createdAt timestamp
  updatedAt timestamp
}

Table Tool {
  id uuid [pk]
  name varchar
  price int 
  stock int 
  imageUrl varchar [null]
  CategoryId uuid 
  ProfileId uuid
  createdAt timestamp
  updatedAt timestamp
}

Ref: Tool.ProfileId > Profile.id // N:1
Ref: Tool.CategoryId > Category.id // N:1